#!/usr/bin/env python
# -*- coding: utf-8 -*-

import pyslicer.exceptions as exceptions

from collections import defaultdict


__mapped_errors = {
    # Authentication and Authorization errors (10 - 19)
    10: exceptions.AuthMissingHeaderException,
    11: exceptions.AuthAPIKeyException,
    12: exceptions.AuthInvalidAPIKeyException,
    13: exceptions.AuthIncorrectPermissionException,
    14: exceptions.AuthInvalidRemoteException,
    15: exceptions.CustomKeyInvalidcolumnCreationException,
    16: exceptions.CustomKeyInvalidPermissionForcolumnException,
    17: exceptions.CustomKeyInvalidOperationException,
    18: exceptions.CustomKeyNotPermittedException,
    19: exceptions.CustomKeyRouteNotPermittedException,
    20: exceptions.DemoApiInvalidEndpointException,
    # Request validations (21 - 29)
    21: exceptions.RequestMissingContentTypeException,
    22: exceptions.RequestIncorrectContentTypeValueException,
    23: exceptions.RequestRateLimitException,
    24: exceptions.RequestInvalidJsonException,
    25: exceptions.RequestInvalidHttpMethodException,
    26: exceptions.RequestInvalidEndpointException,
    27: exceptions.RequestIncorrectHttpException,
    28: exceptions.RequestExceedLimitException,
    # Account Errors (30 - 39)
    30: exceptions.AccountMissingPaymentMethodException,
    31: exceptions.AccountPaymentRequiredException,
    32: exceptions.AccountBannedException,
    33: exceptions.AccountDisabledException,
    39: exceptions.columnInvalidRangeException,
    # column errors (40 - 59)
    40: exceptions.columnMissingParamException,
    41: exceptions.columnTypeException,
    42: exceptions.columnIntegerValuesException,
    43: exceptions.columnAlreadyExistsException,
    44: exceptions.columnLimitException,
    45: exceptions.columnTimeSeriesLimitException,
    46: exceptions.columnTimeSeriesSystemLimitException,
    47: exceptions.columnDecimalTypeException,
    48: exceptions.columnStorageValueException,
    49: exceptions.columnInvalidApiNameException,
    50: exceptions.columnInvalidNameException,
    51: exceptions.columnInvalidDescriptionException,
    52: exceptions.columnExceedDescriptionlengthException,
    53: exceptions.columnInvalidCardinalityException,
    54: exceptions.columnDecimalLimitException,
    55: exceptions.columnRangeLimitException,
    56: exceptions.columnExceededMaxNameLenghtException,
    57: exceptions.columnExceededMaxApiNameLenghtException,
    58: exceptions.columnEmptyEntityIdException,
    59: exceptions.columnExceededPermitedValueException,
    # Insertion errors (60 - 79)
    60: exceptions.InsertInvalidDecimalPlacesException,
    61: exceptions.InsertEntityValueTypeException,
    62: exceptions.InsertcolumnNameTypeException,
    63: exceptions.InsertcolumnTypeException,
    64: exceptions.InsertEntityNameTooBigException,
    65: exceptions.InsertcolumnValueTooBigException,
    66: exceptions.InsertTimeSeriesDateFormatException,
    67: exceptions.InsertcolumnNotActiveException,
    68: exceptions.InsertIdLimitException,
    69: exceptions.InsertcolumnLimitException,
    70: exceptions.InsertDateFormatException,
    71: exceptions.InsertcolumnStringEmptyValueException,
    72: exceptions.InsertcolumnTimeseriesInvalidParameterException,
    73: exceptions.InsertcolumnNumericInvalidValueException,
    74: exceptions.InsertcolumnTimeseriesMissingValueException,
    75: exceptions.QueryTimeSeriesInvalidPrecisionSecondsException,
    76: exceptions.QueryTimeSeriesInvalidPrecisionMinutesException,
    77: exceptions.QueryTimeSeriesInvalidPrecisionHoursException,
    78: exceptions.QueryDateFormatException,
    79: exceptions.QueryRelativeIntervalException,
    # Query errors (80 - 109)
    80: exceptions.QueryMissingQueryException,
    81: exceptions.QueryInvalidTypeException,
    82: exceptions.QueryMissingTypeParamException,
    83: exceptions.QueryInvalidOperatorException,
    84: exceptions.QueryIncorrectOperatorUsageException,
    85: exceptions.QueryColumnNotActiveException,
    86: exceptions.QueryMissingOperatorException,
    87: exceptions.QueryIncompleteException,
    88: exceptions.QueryEventCountQueryException,
    89: exceptions.QueryInvalidMetricException,
    90: exceptions.QueryIntegerException,
    91: exceptions.QueryColumnLimitException,
    92: exceptions.QueryLevelLimitException,
    93: exceptions.QueryBadAggsFormationException,
    94: exceptions.QueryInvalidAggFilterException,
    95: exceptions.QueryMetricsLevelException,
    96: exceptions.QueryTimeSeriesException,
    97: exceptions.QueryMetricsTypeException,
    98: exceptions.QueryContainsNumericException,
    99: exceptions.QueryExistsEntityLimitException,
    100: exceptions.QueryMultipleFiltersException,
    102: exceptions.QueryMissingNameParamException,
    103: exceptions.QuerySavedAlreadyExistsException,
    104: exceptions.QuerySavedNotExistsException,
    105: exceptions.QuerySavedInvalidTypeException,
    106: exceptions.MethodNotAllowedException,
    107: exceptions.QueryExistsMissingIdsException,
    108: exceptions.QueryInvalidFormatException,
    109: exceptions.QueryTopValuesParameterEmptyException,
    110: exceptions.QueryDataExtractionLimitValueException,
    111: exceptions.QueryDataExtractionLimitValueTooBigException,
    112: exceptions.QueryDataExtractionLimitAndPageTokenValueException,
    113: exceptions.QueryDataExtractionPageTokenValueException,
    114: exceptions.QueryDataExtractioncolumnLimitException,
    115: exceptions.QueryExistsEntityEmptyException,
    116: exceptions.QuerySavedInvalidQueryValueException,
    117: exceptions.QuerySavedInvalidCachePeriodValueException,
    118: exceptions.QuerySavedInvalidNameException,
    119: exceptions.QueryCountInvalidParameterException,
    120: exceptions.QueryAggregationInvalidParameterException,
    121: exceptions.QueryAggregationInvalidFilterQueryException,
    122: exceptions.QueryInvalidMinfreqException,
    123: exceptions.QueryExceededMaxNumberQuerysException,
    124: exceptions.QueryInvalidOperatorUsageException,
    125: exceptions.QueryInvalidParameterUsageException,
    126: exceptions.QueryParameterInvalidcolumnUsageException,
    127: exceptions.QueryInvalidcolumnUsageException,
    # Internal errors (110 - 120)
    130: exceptions.InternalException,
    131: exceptions.columnCreateInternalException
}

slicer_exceptions = defaultdict(
    lambda: exceptions.SlicingDiceException,
    __mapped_errors
)
